### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by proimage** [spacecatninja/craft-imager-x-do-spaces-driver#1]
This is an issue from when the plugin was in the hands of @aelvan. https://github.com/aelvan/craft-imager-do-spaces-driver/issues/2

Any idea if this has been fixed in this version?

**Comment by aelvan** [comment]
Still in my hands. And yeah, this has been tested on windows, should work.

**Comment by proimage** [comment]
I've confirmed this seems to be fixed in the -X versions of Imager and its DO Spaces driver. Thank you!!!
